print("Profit Prediction.")
sales = float(input("Enter amount of sales: "))
print("Total sales:", "{:,.2f}".format(sales))
profit = float(sales * 0.21)
print("Expected profit:", "{:,.2f}".format(profit))
